be15-fin-Nexus-SION/be15-fin-Nexus-SION-FE

- tailwind.config.js
#n
---
- tailwind.config.js에 컬러 팔레트 추가
---
- 선택사항
---
Closes #n
> refactor: tailwind.config.js 컬러 팔레트 설정

- src/api/statistics.js
- src/components/SortDropdown.vue
- src/components/searchBar/TechStackSearchBar.vue
- src/components/side/SidebarWrapper.vue
- src/composable/useInfiniteScroll.js
- src/features/statistics/components/AvgList.vue
- src/features/statistics/components/DevList.vue
- src/features/statistics/components/FilterDropdown.vue
- src/features/statistics/components/JobList.vue
- src/features/statistics/components/PopularList.vue
- src/features/statistics/components/SalaryList.vue
- src/features/statistics/components/WaitingCountList.vue
- src/features/statistics/router.js
- src/features/statistics/views/GradeSalaryView.vue
- src/features/statistics/views/StackAvgCareerView.vue
- src/features/statistics/views/StackMemberCountView.vue
- src/features/statistics/views/StackPopularView.vue
- src/features/statistics/views/WaitingCountView.vue
Closes #14 
<br>
등급별 연봉 조회 페이지 구현
드롭다운 스타일 변경
테스트 코드는 후에 작성
<br>
<br>
> [feat] 등급별 연봉 조회 페이지 구현

- src/api/admin.js
- src/assets/main.css
- src/components/input/InputBox.vue
- src/components/searchBar/NameIndexBar.vue
- src/components/side/SidebarWrapper.vue
- src/features/admin/components/AdminJobsList.vue
- src/features/admin/router.js
- src/features/admin/views/AdminJobsView.vue
- src/utills/hangul.js
- src/utills/toast.js
- tailwind.config.js
Closes #43
<br>
직무 목록 조회, 추가 페이지를 구현했습니다.
초성으로 자동 스크롤이 되는 기능도 추가로 구현했습니다.
<br>
<br>
> [feat] 직무 목록 조회, 추가 페이지 구현

- src/api/admin.js
- src/components/input/InputBox.vue
- src/components/side/SidebarWrapper.vue
- src/features/admin/components/AdminTechStacksList.vue
- src/features/admin/router.js
- src/features/admin/views/AdminDomainsView.vue
- src/features/admin/views/AdminJobsView.vue
- src/features/admin/views/AdminTechStacksView.vue
Closes #52
<br>
관리자가 기술 스택을 조회, 추가, 삭제할 수 있는 페이지를 구현했습니다.
<br>
<br>
> [feat] 기술 스택 관리 페이지 구현

- src/assets/icons/Circle_Check.svg
- src/composable/useInfiniteScroll.js
- src/features/admin/views/SetGradePerUnitPriceView.vue
- src/features/squad/components/ExistSquadCard.vue
- src/features/squad/components/ExistSquadModal.vue
Closes #90 
<br>
- ai, 일반 카드 레이아웃 구현 완료
- 선택 모션 구현완료
- 선택하기 클릭 시 정보 전송 구현완료
<br>
<br>
> 기존 스쿼드 가져오기 모달 생성

- src/features/squad/components/SquadCard.vue
- src/features/squad/components/SquadInfo.vue
- src/features/squad/components/SquadSidebar.vue
- src/features/squad/components/SquadSidebarSection.vue
- src/features/squad/components/create/AiRecommendedSection.vue
- src/features/squad/components/create/ManualDeveloperList.vue
- src/features/squad/components/create/SquadFilterSection.vue
- src/features/squad/views/SquadDetailView.vue
- src/features/squad/views/SquadListView.vue
- 애니메이션 및 디자인 관련 기능들을 추가했습니다. 
<br>
- 선택사항
<br>
- [o] 이슈 완료
> [Feat] 스쿼드 애니메이션 기능 추가

- src/components/badge/ProjectHistoryStatusBadge.vue
Closes #n
<br>
내용작성
<br>
- 선택사항
<br>
> feat: 거부 뱃지 label 내용 수정

- src/api/member.js
- src/components/header/AuthMenu.vue
- src/features/auth/views/LoginView.vue
- src/features/developer/components/DeveloperFormCard.vue
- src/stores/auth.js
Closes #87
<br>
헤더에 프로필 뜨도록 수정
<br>
- 선택사항
<br>
> [fix] 헤더에 프로필 뜨도록 수정

- src/components/header/AuthMenu.vue
- src/components/header/HeaderNav.vue
- src/features/notification/components/NotificationModal.vue
Closes #182
<br>
헤더에서 알림 삭제, 마이페이지 추가, 프로필 모달 수정
<br>
- 선택사항
<br>
> fix: 헤더에서 알림 삭제, 마이페이지 추가, 프로필 모달 수정

- src/features/project/router.js
> [fix] fix project router.js

- src/features/developer/components/BarChart.vue
- src/features/developer/views/DeveloperDetailView.vue
Closes #196
<br>
- 등급 글씨 키우기
- 상태 뱃지 수정
- 그래프 색상 통계와 맞춤
<br>
- 선택사항
<br>
> [fix] 개발자 상세 페이지 수정

- src/features/admin/views/AdminCertificateApprovalView.vue
- src/features/admin/views/AdminCertificateTypeSetting.vue
- src/features/developer/views/DeveloperCertificateTypeListView.vue
- src/features/developer/views/DeveloperListView.vue
- src/features/developer/views/DeveloperOwnedCertificateView.vue
- src/features/squad/components/create/ManualDeveloperList.vue
- src/features/squad/components/modal/FilterModal.vue
Closes #197
<br>
- 뱃지 리펙토링
- 자격증 관련 페이지 릭페토링(가운데 정렬, toast)
<br>
- 선택사항
<br>
> [refactor] 상태 뱃지 추가, 자격증 관련 페이지 리펙토링

- src/api/notificationSse.js
> refactor: sse 설정 리팩토링

- src/features/project/components/FilterSidebar.vue
- src/features/project/components/ProjectCard.vue
- src/features/project/components/StatusIndicator.vue
- src/features/project/views/ProjectListView.vue
Closes #204 
<br>
프로젝트 상태에서 추가된 '평가중' 에 대한 표기를 추가했습니다.
<br>
- 선택사항
<br>
> refactor: 프로젝트 상태 '평가중' 추가 및 색상 통합

- src/features/project/views/ProjectDetailView.vue
- src/features/squad/components/create/ManualDeveloperList.vue
- 대기중일땐 종료 버튼 나오도록 변경
<br>
- 선택사항
<br>
> [Refactor] 프로젝트 세부사항 페이지에서 버튼 수정

- src/components/list/DevListItem.vue
- src/features/statistics/components/DevList.vue
Closes #208
<br>
- 통계에서 개발자 item 누르면 해당 개발자 상세 페이지로 연결
- 스타일을 개발자 리스트와 통합
<br>
- 선택사항
<br>
> [refactor] 통계에서 개발자 item 누르면 해당 개발자 상세 페이지로 연결 & 스타일을 개발자 리스트와 통합

- src/features/project/views/ProjectRegisterView.vue
Closes #212
<br>
프로젝트 등록 페이지 리펙토링 했습니다.
전체적으로 스타일을 개발자 등록과 프로젝트 등록의 스타일과 맞췄습니다.
성용씨가 부탁한 기술 스택별로 필요 인원 입력을 필수로 두는 것은 이미 되어 있어서 db 에서 해당 컬럼을 not null 로 설정해두는 것만 수정했습니다.
추가로 시작일이 종료일보다 앞서면 showErrorToast 가 뜨도록 코드 넣어놨습니다.
<br>
- 선택사항
<br>
> refactor: 프로젝트 등록 페이지 리펙토링

- src/components/badge/StatusBadge.vue
Closes #220
<br>
라벨 내용 미투입 -> 비활성 으로 수정했습니다.
<br>
- 선택사항
<br>
> refactor: 라벨 이름 바꿈

- src/features/auth/components/LoginForm.vue
- src/features/auth/components/SignupForm.vue
Closes #224 
<br>
<br>
- 선택사항
<br>
> refactor: 로그인 및 회원가입 버튼 색 수정

- src/composable/useValidation.js
- src/features/auth/components/SignupForm.vue
Closes #225 
<br>
내용작성
<br>
- 선택사항
<br>
> refactor: 생년월일 타입을 text로 변경 후 validator 설정

- src/features/developer/components/CertificateList.vue
Closes #240 
<br>
내용작성
<br>
- 선택사항
<br>
> feat: 자격증 목록에 스크롤 추가

- src/api/notificationSse.js
- src/features/developer/components/CertificateList.vue
- src/features/developer/views/DeveloperDetailView.vue
- src/features/freelancer/views/FreelancerListView.vue
- src/features/project/components/ReplacementDeveloperSearch.vue
- src/features/project/views/ProjectRegisterView.vue
- src/features/squad/components/SquadSidebar.vue
> feat: error, warning 로그 제외 console.log 제거.

- src/features/developer/components/CertificateList.vue
Closes #n
<br>
내용작성
<br>
- 선택사항
<br>
> feat:스크롤 높이 수정

- src/api/squad.js
- src/features/project/components/ProjectEditForm.vue
- src/features/project/views/ProjectDetailView.vue
- src/features/squad/components/create/ManualDeveloperList.vue
- src/features/squad/components/presentation/SquadMemberRenderer.vue
Closes #263
<br>
프로젝트 수정 시 프로젝트 종료 날짜 보이게 수정
<br>
- 선택사항
<br>
> [fix] 프로젝트 종료 날짜 보이게 수정

- src/features/project/views/ProjectDetailView.vue
- src/features/squad/components/create/SquadCreateSection.vue
Closes #n
<br>
내용작성
<br>
- 선택사항
<br>
> refactor: 쿼리문에 string으로 null 이라고 들어가고있던 부분 수정

- src/features/project/components/SquadCard.vue
- src/features/project/views/ProjectDetailView.vue
Closes #287 
<br>
내용작성
<br>
- 선택사항
<br>
> refactor: 분기점 추가

- src/features/project/views/ProjectDetailView.vue
- src/features/squad/views/SquadListView.vue
Closes #292 
<br>
- 사이드바 높이 조정
- 프로젝트 상세에서 프로젝트 상태가 시작전일 때 프로젝트 종료, 평가 완료 버튼 안 보이게 수정
<br>
- 선택사항
<br>
> fix: 스쿼드 사이드바, 프로젝트 상세 버튼 수정

- src/features/squad/views/SquadDetailView.vue
- src/features/squad/views/SquadListView.vue
Closes #299
<br>
스쿼드 스타일, 프로젝트 제목 뜨도록 수정
<br>
- 선택사항
<br>
> fix: 기술 스택별 구성원 조회 기능 수정

- src/features/squad/components/presentation/SquadMemberRenderer.vue
Closes #n
<br>
내용작성
<br>
- 선택사항
<br>
> refactor: update suqad detail view layout

- src/features/project/components/SquadCard.vue
Closes #302
<br>
스쿼드 카드 내 버튼 위치 수정
<br>
- 선택사항
<br>
> fix: 버튼 위치 수정
